package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 26 11:45:32 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WpSectionCapacityVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public WpSectionCapacityVOImpl() {
    }
}
